### ISSUE TITLE
Watt is not returning a real promise, chaining is not possible

### ISSUE THREAD

**Issue by Skywalker13** [mappum/watt#15]
Hello,

It's based on your example in the README:

``` js
'use strict';

const watt = require ('watt');

const foo = watt (function * (next) {
  setTimeout (next, 1000)
  return 'aslfdkj'
});

const bar = watt (function * (next) {
  return yield foo () // 'next' not necessary
});

// callers can use the Promise API instead of a callback if they want
bar ().then (res => console.log (res)).catch (err => console.error (err))
```

I want to add `catch()` after `then()` but it's not possible.

```
bar ().then (res => console.log (res)).catch (err => console.error (err))
                                      ^

TypeError: Cannot read property 'catch' of undefined
    at Object.<anonymous> (/home/schroeterm/devel/test.js:15:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by cshum** [comment]
What about 
* wrapping the WattPromise (that throws error if not handled) as separated module
* accept Promise type as option, using native Promise by default?

**Comment by Skywalker13** [comment]
Not sure to understand what you mean; the WattPromise that I've done is extending the native Promise: https://github.com/mappum/watt/pull/18/files and (according to @mappum it's "slow" and) it works only with nodejs >= 6 (https://github.com/mappum/watt/pull/18#issuecomment-239220685).
