### ISSUE TITLE
The exception is lost if a finally returns something

### ISSUE THREAD

**Issue by Skywalker13** [mappum/watt#16]
``` js
const watt = require ('watt');

const a = watt (function * () {
  throw new Error ('the exception');
});

const b = watt (function * () {
  try {
    yield a ();
  } catch (ex) {
    throw ex;
  } finally {
    return 'finally';
  }
});

b ((err, res) => {
  console.log (res);
  console.log (err);
});
```

output (error lost):

```
finally
null
```

---

If I remove the return in finally:

``` js
  } finally {
    // return 'finally';
  }
```

output (error received):

```
undefined
Error: the exception
    at /home/schroeterm/devel/test.js:5:9
    at next (native)
    at Immediate.err (/home/schroeterm/devel/node_modules/watt/index.js:134:31)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by Skywalker13** [comment]
Sorry for the noise, I close it.

It seems that it's the normal behaviour...
This simple code prints 'b' and nothing else.

``` js
'use strict';

function a () {
  try {
    throw 'a';
  } catch (ex) {
    throw ex;
  } finally {
    return 'b';
  }
}

try {
  console.log (a ());
} catch (ex) {
  console.error (ex)
}
```
